### ISSUE TITLE
Failing test on clone in Qa::SubjectMesh

### ISSUE THREAD

**Issue by hackmastera** [projecthydra-labs/questioning_authority#115] opened 2016-10-24 17:34 UTC
Cloned, ran tests according to README. Got this failure. The build is passing; is there some step missing in setup?

```
  1) Qa::SubjectMeshTerm finds a term by tree number
     Failure/Error: t.save!

     ActiveRecord::RecordInvalid:
       Validation failed: Subject mesh term must exist
     # ./spec/models/subject_mesh_term_spec.rb:30:in `block (2 levels) in <top (required)>'
```

**Comment by awead** [comment] 2016-10-25 14:32
Weird. I don't get that:

    git clone https://github.com/projecthydra-labs/questioning_authority
    cd questioning_authority/
    bundle update
    bundle exec rake engine_cart:generate
    bundle exec rspec

Tests are randomized. Are you able to repeat the error with a specific seed setting?

**Comment by hackmastera** [comment] 2016-10-25 17:41
I'm getting this failure every time i run. here is the last seed it gave me:

**Comment by mjgiarlo** [comment] 2017-03-21 21:29
@hackmastera @awead Could not reproduce even with the same seed. Closing for now.

**Closed by mjgiarlo** 2017-03-21 21:29 UTC
